### ISSUE TITLE
[oc-check-dns] Change arguments to unix style - only for one letter and -- for words

### ISSUE THREAD

**Issue by rbo** [RedHat-EMEA-SSA-Team/stc4#1]
To be more conform with UNIX we have to change the arguments from `-api` to `--api`  

one `-` only for single characters to allow to combine like `-xac`. For words we have to use `--`

**Comment by ralvares** [comment]
Package flag implements command-line flag parsing.

Golang Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--". 

There are 4 alternative already working.

-count=x
-count x
--count=x
--count x

You can pass as many flags as you want to a command, but the first time flag does not recognize a flag, it will stop parsing the additional ones. This means that flags must all go at the beginning, if you have non-flag parameters as well.

I'll check other possibilities to improve the arguments
